default: &default
  adapter: redis
  url: <%= ENV.fetch("VOQALAPP_REDIS_URL") { 'redis://localhost:6379/1' } %>

development:
  <<: *default
  channel_prefix: voqalapp_development

test:
  <<: *default
  channel_prefix: voqalapp_test

production:
  <<: *default
  channel_prefix: voqalapp_production
