default: &default
  adapter: redis
  url: <%= ENV.fetch("VIKYAPP_ACTIONCABLE_REDIS_URL") { 'redis://localhost:6379/1' } %>

development:
  <<: *default
  channel_prefix: vikyapp_development

test:
  <<: *default
  channel_prefix: vikyapp_test

production:
  <<: *default
  channel_prefix: vikyapp_production
