default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("VIKYAPP_DB_HOST") { 'localhost' } %>
  port: <%= ENV.fetch("VIKYAPP_DB_PORT") { 5432 } %>
  username: <%= ENV.fetch("VIKYAPP_DB_USERNAME") { 'viky' } %>
  password: <%= ENV.fetch("VIKYAPP_DB_PASSWORD") { 'viky' } %>

development:
  <<: *default
  database: <%= ENV.fetch("VIKYAPP_DB_NAME_DEV") { 'vikyapp_development' } %>

test:
  <<: *default
  database: vikyapp_test

production:
  <<: *default
  database: <%= ENV.fetch("VIKYAPP_DB_NAME") { 'vikyapp_production' } %>
  timeout: 1500
