---
:concurrency: <%= ENV.fetch("VIKYAPP_SIDEKIQ_CONCURRENCY") { 5 } %>
:pidfile: ./tmp/pids/sidekiq.pid
:queues:
  - [webapp_mailers, 2]
  - webapp_default
  - webapp_bot
  - webapp_agent_regression_checks

