default: &default
  client:
    hosts: <%= ENV.fetch("VIKYAPP_STATISTICS_HOSTS") { ['localhost:9200'] } %>

production:
  <<: *default

development:
  <<: *default

test:
  <<: *default
  client:
    hosts: ['localhost:9222']
