stages:
  - build
  - test
  - docker_push

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  VOQALNLS_DOCKER_IMAGE: docker-registry.pertimm.corp:50001/voqal.ai/platform/nls
  DOCKER_DRIVER: overlay

# Build docker image
build_nls_image:
  stage: build
  image: docker:dind
  script:
    - docker build --target run_image  -t ${VOQALNLS_DOCKER_IMAGE}:${CI_COMMIT_REF_SLUG} pse
    - docker push ${VOQALNLS_DOCKER_IMAGE}:${CI_COMMIT_REF_SLUG}
    - docker build --target test_image -t ${VOQALNLS_DOCKER_IMAGE}_test:${CI_COMMIT_REF_SLUG} pse
    - docker push ${VOQALNLS_DOCKER_IMAGE}_test:${CI_COMMIT_REF_SLUG}

# Test docker image
test_nls:
  stage: test
  image: ${VOQALNLS_DOCKER_IMAGE}_test:${CI_COMMIT_REF_SLUG}
  variables:
    GIT_STRATEGY: none
  script:
    - bundle exec rake test

# Push tested docker image
docker_push:
  stage: docker_push
  image: docker:dind
  variables:
    GIT_STRATEGY: none
  script:
    - docker tag ${VOQALNLS_DOCKER_IMAGE}:${CI_COMMIT_REF_SLUG} ${VOQALNLS_DOCKER_IMAGE}:latest
    - docker push ${VOQALNLS_DOCKER_IMAGE}:latest
